steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/strava-oauth', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/strava-oauth']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      - 'run'
      - 'deploy'
      - 'strava-oauth'
      - '--image'
      - 'gcr.io/$PROJECT_ID/strava-oauth'
      - '--platform'
      - 'managed'
      - '--region'
      - 'europe-west1'
      - '--allow-unauthenticated'
      - '--timeout'
      - '300s'
      - '--update-secrets'
      - 'STRAVA_CLIENT_ID=STRAVA_CLIENT_ID:latest,STRAVA_CLIENT_SECRET=STRAVA_CLIENT_SECRET:latest,REDIRECT_URI=REDIRECT_URI:latest'
      - '--service-account'
      - 'strava-oauth-sa@wly-customer-strava-aggregator.iam.gserviceaccount.com'

images:
  - 'gcr.io/$PROJECT_ID/strava-oauth'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '900s'